### ISSUE TITLE
People lists on pages are not links

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#105]
**Describe the bug**
The People lists, autogenerated, have a photo and name, but you cannot click on them to get to a people page.

**To Reproduce (if applicable)**
Click on Francesco shown at the bottom of the page https://www.ai-for-health.nl/vacancies/deep-learning-lung-immune-therapy/

**Additional context**
I assume this was not implemented because it is not directly clear to which subsite’s people page you link in this case. My proposal is to have a ‘default’ site for every people entry, as a line on top of his people md page. Francesco could go to computational pathology.

**Comment by martvanrijthoven** [comment]
Thanks for the bug report! It seemed like the problem was caused by not having a member page on the site. Hence no members were copied to the website repo . I fixed this by copying all members to the ai-for-health repo in the build script.

**Comment by bramvanginneken** [comment]
Thanks! I start to understand the design philosophy. One thing leads to another: now the bio page of Francesa co and Henkjan exist, but they have a link to publications and the publication pages give an error.

**Comment by martvanrijthoven** [comment]
Aha Yes the publications were disabled for ai-for-health. Its enabled now :)

**Comment by martvanrijthoven** [comment]
However, it seems it does not work here https://www.ai-for-health.nl/publications/bram_van_ginneken/
I will investigate why this does not work

**Comment by wouterbulten** [comment]
Hi Bram and Mart, this is indeed a problem caused by our "separate site" design: each website is independent and people pages are not generated if they are not part of the website. Mart's fix to copy all the people pages is a good temporary solution which fixes it for now. I do think we can make something more clean for the future.  We will see this problem occurring more often with shared vacancies, projects that span across groups, etc.

I like Bram's suggestion to add a "default" group variable to each person. It's a bit more work, though this will fix the problem not only for AI-in-health but also for the other websites. Moreover, this would also result in a lot less duplicate content across websites. Which is a good thing, given that search engines can penalize pages with similar/equal content and show them lower in the search results. The less people pages for a single person we have the better. We could even use this variable in the site's design, for example by showing group membership on project pages or vacancies.

@martvanrijthoven let's discuss this during the week?

**Comment by martvanrijthoven** [comment]
Yes sure good idea!

**Comment by wouterbulten** [comment]
I've fixed this issue. All vacancies can now link to people pages of other websites. The link is based on the 'default_group' variable that can be set for each user. If none is set, it defaults to diag. 

See for example https://www.ai-for-health.nl/vacancies/aimaster-interventional-mri/
