### ISSUE TITLE
Publications Clarisa missing

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#126]
All publications from Clarisa are missing. Her last name is always written with an accent in diag.bib, as is in her .md file etc.

**Comment by ghumpire** [comment]
I believe this happens because of the difference between "Clarisa Sánchez" (how appears in the people/ folder) and "Clara Isabel Sánchez" (how appears in the publications). See the following publications:
- https://www.sciencedirect.com/science/article/pii/S0161642019306578?via%3Dihub
- https://www.osapublishing.org/boe/abstract.cfm?uri=boe-9-4-1545

At this moment, the bibparser identifies Clarisa as first name and Sánchez as the last name, the problem is that we need 'Clara' instead of 'Clarisa'. One hacky solution would be replacing every person with the first name 'Clarisa' (only one person, right?) and change it to 'Clara'. That way, the parser will have 'Clara Sánchez' and will show her publications. A more elegant solution would be considering nicknames as authors.

The easiest solution would be renaming the md file to clara-sanchez.md or something like that but then Clarisa will appear on the website as "Clara Sánchez".

**Comment by martvanrijthoven** [comment]
I fixed this with an optional pub_name tag
