### ISSUE TITLE
Collaborations section in Retina website

### ISSUE THREAD

**Issue by CristinaGGonzalo** [DIAGNijmegen/website-content#133]
Would it be possible to add a "Collaborations" section within the "Projects" tab for the Retina website? It would include the institutions with which the group collaborates in the present and perhaps also the ones with which there was a collaboration in the past.

It would be after the "Projects & Software" section (after Current, Software, and Finished subsections).

**Comment by wouterbulten** [comment]
@CristinaGGonzalo do these need to be in the same card format as the software/projects? Or can they be a list of logo's/text?

**Comment by CristinaGGonzalo** [comment]
@wouterbulten each collaboration listed could be a logo and a text below with the name of the collaborator. Then, if the logo/text is clicked, a page with the description of the collaboration would open (as when clicking on a given project card).

**Comment by wouterbulten** [comment]
Because it is so specific, probably the most easiest option is to create a custom projects page and add content to this. I have added a new option `content_after` that makes sure to output content after the projects/software cards. 

@CristinaGGonzalo I have created a custom page for the retina website (see https://github.com/DIAGNijmegen/website-content/blob/master/website-retina/content/pages/projects.md). You can add content there and it will show up below the projects (see https://www.a-eyeresearch.nl/projects/). Custom pages can be made in the same folder (e.g., pages/collaborations/something.md), you can then link to these from the projects page.

**Comment by wouterbulten** [comment]
Assigning the issue to @CristinaGGonzalo. Let me know when this suits your use case.

**Comment by wouterbulten** [comment]
Closing this issue as the feature was implemented.
