### ISSUE TITLE
Copy covers of phd thesis to content repo

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#203]

**Comment by wouterbulten** [comment]
We already make a page for a phd thesis with an image. We should make sure that the bibparser does not generate two pages for each thesis, instead all links should go to the correct page.

**Comment by wouterbulten** [comment]
@martvanrijthoven can you take a look at this?

**Comment by wouterbulten** [comment]
@martvanrijthoven maybe this issue is invalid. The thesis from Babak for example already shows the image: https://www.computationalpathologygroup.eu/publications/bejn17a/ We probably have many thesis entries without images?

**Comment by martvanrijthoven** [comment]
Yes i think some don't have covers but still, something is wrong see:

http://diagnijmegen.nl/index.php/Publication?bibkey=Meij20
https://beta.diagnijmegen.nl/publications/meij20/

**Comment by wouterbulten** [comment]
Todo: transfer covers of theses to the repo.

**Comment by martvanrijthoven** [comment]
@coendevente  i tried to create png thesis images with pdf2image (from the pdfs), but i am having trouble with the getting PDFPageCountError for every pdf file. Did you also encounter this and if so, could you tell me how to solve this? Tia

**Comment by coendevente** [comment]
I haven't worked with pdf2image, Bram did. @bramvanginneken did you not get any PDFPageCountError?

**Comment by wouterbulten** [comment]
I just uploaded the thesis covers to repo.

In the future we could make a link with the literature repo, but this should tie in to the image optimizer pipeline and will require some additional work.

**Comment by sjoerdk** [comment]
Just to be sure. Is this correct? 
DIAG theses will now be maintained by DIAG and no longer be updated here: http://radboudimaging.nl/index.php/Theses

**Comment by bramvanginneken** [comment]
Good point. I would say the maintainers of radboudimaging.nl (is that you?) should update this if Radboudimaging wants to keep this up to date. Just like the publications are kept up to date separately by the secretary who types this in directly.

Also the biographies and list of people for DIAG personnel on radboudimaging.nl will not be kept up to date because we do not edit the excel spreadsheet anymore now that we have moved to the new DIAG site. I suggest to have a meeting with who maintains radboudimaging.nl what to do. At least the links to publications on diag bio pages need to be removed, because this will not be updated anymore. The bio texts could be manually synced by the secretaries every 6 months or so, should that be desired. Maybe just putting a link to the bio page on diagnijmegen.nl is more practical.

**Comment by wouterbulten** [comment]
We have migrated the covers. Issue can be closed now.
