### ISSUE TITLE
Upload image fails (stephan dooper)

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#335]
The commit gives an error at "Run stefanzweifel/git-auto-commit-action@v4". I have locally pulled and pushed the repository and restarted the job, but this did not help.

**Comment by martvanrijthoven** [comment]
Hi Meyke, 

you mean the optimize image failure: https://github.com/DIAGNijmegen/website-content/actions/runs/534475242 ?

This is caused when committing new files when optimize image is still running (it can not push because it first should pull). I still have to fixed this in the build pipeline.  Note that this error is only causing images not to be optimized. For now, manual triggering can fix this. I did it  (https://github.com/DIAGNijmegen/website-content/actions/runs/534817427).

**Comment by martvanrijthoven** [comment]
this issue will be tracekd here #323
