### ISSUE TITLE
Redirect edit for news items is not working

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#365]
The edit button on news items will not redirect to the .md edit page on github

e.g.,
https://www.diagnijmegen.nl/news/eurrad-100-ai-products/

-->

https://github.com/diagnijmegen/website-content/edit/master/website-diag/content/news/eurrad-100-ai-products.md

**Comment by martvanrijthoven** [comment]
Hi Natalia,

It seems that replacing highlights with news, already solved the problem, so you actually already solved it. Not sure why it did not work on your local machine. Anyway you can see the exact change via the commit: https://github.com/DIAGNijmegen/website-content/commit/f5d148547a0b7ca0429ad99a7dec1c9f4b49268d

**Comment by NataliaAlves13** [comment]
@martvanrijthoven the problem is in the website-content\plugins\edit_url\pelican_edit_url.py file. Cchanging "highlights" to "news" in the shared_dirs and replacing
 instance.edit_url = EDIT_CONTENT_URL.format(file_path=rel_file_path).replace('/content/news', '/content/pages/news')
with
instance.edit_url = EDIT_CONTENT_URL.format(file_path=rel_file_path).replace('news', 'pages/news')
Solves the problem. There seems to be a problem with the replace function although I couldn't point out what it is yet.

**Comment by NataliaAlves13** [comment]
> Hi Natalia,
> 
> It seems that replacing highlights with news, already solved the problem, so you actually already solved it. Not sure why it did not work on your local machine. Anyway you can see the exact change via the commit: [f5d1485](https://github.com/DIAGNijmegen/website-content/commit/f5d148547a0b7ca0429ad99a7dec1c9f4b49268d)

Ok makes sense, seems to be a problem with the replace function and the "/" character, although I don't understand why it's not working! But great that it's solved

**Comment by martvanrijthoven** [comment]
Aha, the "/" could be an issue with Windows/Linux, maybe.
