### ISSUE TITLE
automatic update of diag.bib

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#472]
- is there an API?
- save search results and cross check with script (every 6 months or so)

**Comment by keelinm** [comment]
Pubmed can email results of a specified search on a regular basis (e.g. search by affiliation radboudumc and year published).  From this you can save the results to a csv through one (or a few?!) clicks.   Discussed today that this could be done periodically and a script could match diag members by name and publications not already on our website.   Rather than automatically updating diag.bib a safer solution may be to auto-email the diag members in question, ask if it is their publication and provide the bibtex snippet to be added to diag.bib.  They should then add it themselves if it is theirs.

**Comment by keelinm** [comment]
Per meeting 21 Sept:
Add if missing, update if e.g. volume/page numbers have recently been added
Need to check whether we can search only in last 6 months (e.g.)
Need to check if/how we could send email to supposed author, or if it is better to just review them ourselves and email if needed

**Comment by keelinm** [comment]
I discussed with Bram recently, various topics on keeping literature up to date and accessible on the website.  I will write the outcomes of the conversation here - these can later be split out into different, independent tasks. 
1) We should use "publish or perish" software to generate csv files of what literature *should* be on the website (this idea replaces the idea above to do pubmed search, since "publish or perish" can also include google scholar search).  The use of "publish or perish" will be manual - I don't think there is an API for this - so will need to be done periodically. 
2) We make a script to update the literature on the website based on the content of the "publish or perish" csv file. 
3) Provision of pdf files of our publications is important:
 - if the paper is open access then indicate this with a field in the bib file, and in that case the "DOI" button should say "DOI - open access" so the viewer knows they can reach the full paper through this link.  (We could hire a student to retrospectively update the current bib file entries)
 - if the paper is not open access and is not provided via Taverne link then we should provide the pdf ourselves (storing them e.g. on the google drive of the webteam google account).  This is the case also for abstracts and conference papers.

**Comment by keelinm** [comment]
Mart remarks we should discuss with James as he has a proposed solution - we will discuss with him in January

**Comment by jmsmkn** [comment]
What we do on Grand Challenge, using https://www.crossref.org/documentation/cited-by/.

- For each publication we store an identifier, either a DOI or an ArxivID (could use the DOIs there now too): https://github.com/comic/grand-challenge.org/blob/850038a3e005d14a9946743d84d7d80bb528a2be/app/grandchallenge/publications/models.py#L38-L41
- Every night we run a task to update the metadata for the publication:
  - https://github.com/comic/grand-challenge.org/blob/850038a3e005d14a9946743d84d7d80bb528a2be/app/grandchallenge/publications/tasks.py#L15-L24
  - We query the metadata from either the DOI system itself, or Arxiv https://github.com/comic/grand-challenge.org/blob/850038a3e005d14a9946743d84d7d80bb528a2be/app/grandchallenge/publications/fields.py#L54-L77
  - This might return a new identifier, for instance if an Arxiv paper is published it gets a proper DOI, so we replace the identifier and get further metadata for the publication from the new location
  - The metadata is stored in the database in [Citation Style Language](https://citationstyles.org/) format https://github.com/comic/grand-challenge.org/blob/850038a3e005d14a9946743d84d7d80bb528a2be/app/grandchallenge/publications/tasks.py#L26-L28
  - Note that converting Arxiv to CSL is a bit of a pain, but maybe that is better now they have DOIs, but would need to see how things are handled with the DOI tracking once an arxiv paper is published https://github.com/comic/grand-challenge.org/blob/850038a3e005d14a9946743d84d7d80bb528a2be/app/grandchallenge/publications/utils/manubot.py#L109
- From each publications metadata we can extract the number of citations (`"is_referenced_by_count"`) and store that as a separate value on the model https://github.com/comic/grand-challenge.org/blob/850038a3e005d14a9946743d84d7d80bb528a2be/app/grandchallenge/publications/models.py#L66-L78, see also https://github.com/CrossRef/rest-api-doc/blob/master/api_format.md

**Comment by jmsmkn** [comment]
Result is this, probably you want to compare the citation counts with your sources:

![image](https://user-images.githubusercontent.com/12661555/216016149-02b15947-3e12-46ea-9e38-a5f585392a34.png)

**Comment by keelinm** [comment]
I looked into a few options comparable to "publish or perish" since that has limitations meaning that having a scripted interface with it is not easy, and so it needs to be run as a gui on a windows machine to produce a csv file. 

I like https://www.semanticscholar.org/ - it has an API - we could search it by author name/id and it has very similar results to google scholar, although it does not include abstracts.   It gets publication information from a large number of partners https://www.semanticscholar.org/about/publishers.  There is also already a nice python library built on it https://github.com/danielnsilva/semanticscholar

To include all google scholar results including abstracts we can also look at scholarly https://github.com/scholarly-python-package/scholarly   This has an option to use proxies so that google does not block the IP address making multiple consecutive requests.

Need to do further investigation to compare these things directly with each other and with "publish or perish" to see how the results from various searches look.

**Comment by bramvanginneken** [comment]
I think the procedure suggested by James looks very promising. This is open data, and I think the quality of crossref results has improved a lot. I also see journal using this to provide extra info on their website. Google scholar does not have an api and limits scraping and excessive access, publish or perish does its best to circumvent this. For a long time google scholar was far ahead of the competition but maybe now is the time to switch to a proper open database provided by the scientific community. Semantic scholar is by the Allen institute, the former Microsoft boss turned philantropist who made this mouse brain atlas, If I search for my publications I am not impressed, it has my papers under many names and spellings, does not find Geert’s review, my most cited paper, even though it is in their database, they have listed me with a wrong name but the pdf and pubmed link they provide has my name correctly. I did not check it further.

**Comment by keelinm** [comment]
@jmsmkn just to be clear, you do not use crossref for searching for publications, only for getting citation numbers on publications you have added there?   If I search by author I do not get very extensive results, so I don't think it will fit our needs for searching for new publications.... (unless we ask everyone to put their publications there, which would be good, but has the same issues as asking everyone to put their own publications on the website.....)

**Comment by jmsmkn** [comment]
Yes, only for citation information, we ask people to provide a DOI or ArXiv ID and do the rest. See https://grand-challenge.org/publications/create/ and https://grand-challenge.org/publications/.

**Comment by keelinm** [comment]
Summary of our findings/discussion so far: @bramvanginneken maybe we can discuss your thoughts on this?

Options I have checked out:

CrossRef
Seems like a nice idea and has a REST API for querying.  I’m not convinced how reliable it is to query by author name though.  I queried https://api.crossref.org/works?query.author=bram+van+ginneken&sort=score&order=desc&offset=0 and went over all the pages with increasing offset numbers (there are 1.3 million results!).  First pages of results are promising, then it starts giving results from all kinds of different authors and fields, and then pages later it comes with more correct finds - important and recent papers.   After about 5 minutes (when I stopped it) there are about 330 papers which seem to be correctly from Bram, but this is not very efficient if you only want to check for new publications.  I have tried to order by date and it does not seem to work well.  It also did not return me a paper which I see does exist in its database, (possibly because the name on it is B van Ginneken).  There is no “author ID” attached to a particular author in this system as far as I can see so it relies on name matching.
It does not appear to do abstracts and although it does cover arxiv it was missing several papers that I particularly looked for there.

Semantic Scholar
Disclaimer: I have not yet tried the scripted interface here so have yet to see how efficiently that works.  However it assigns an ID to specific authors and as Bram pointed out, it has assigned several IDs to him, with slightly different names!  However between B van Ginneken and B Ginneken there are a total of 569 publications so I think there is good coverage there.  If we use this system we should store any known ID(s) for all our members to make sure we cover all their publications correctly.   Compared to google scholar it has 8 of 9 of Bram’s 2023 publications (the 9th one is a Master thesis) and I was able to find any other papers that I searched for specifically, which was not the case with crossref. 
It does not cover abstracts as far as I can see. 

Scholarly:
Scholarly gives a pythonic interface to google scholar and mainly uses proxies to avoid being detected.  This would allow us to pick up all google scholar papers and also to use author IDs rather than relying on name matching.  I was not able to get the proxy side of things working when I tried it.  However, I was able to use it to do short requests like “publications of Bram van Ginneken, sorted by year, only the last 40 items” which is quick and doesn’t require multiple pages of data, and would include all recent (new) publications.   Even without proxies I think we could do our searches with time delays between them and not run into issues……
We discussed in our meeting whether this approach is safe/legal since Google clearly does not want bots accessing google scholar.  I think since we will not be doing any excessive searching it should not be an issue and if we can do it undetected then it would be fine, but I leave it to Bram to consider. 

As a qualitative result, here are sample things that I tried to find in all 3 systems.  Green means I found it, orange means I did not.
![image](https://user-images.githubusercontent.com/6442576/220676737-7c971370-5fff-48c4-984e-9bcb94e63dcb.png)

**Comment by keelinm** [comment]
Thanks @jmsmkn  I will give that a try just to see how it compares.  On the topic of crossref - should it include arxiv papers - I do not find any!  What do you do with those - for citation counts I mean?  Bram is in favour of looking into crossref further, and maybe using the same system that you have, where the authors should enter their publications by DOI - which would eliminate the issues with its search functions.

**Comment by jmsmkn** [comment]
No unfortunately ArXiv does not provide that information.

**Comment by keelinm** [comment]
We will follow a two-prong approach for this.  
1: Anyone can add a publication via an interface where they provide a DOI .  (Later we may also allow addition of abstracts or other no-DOI publications via such an interface).
2: We will regularly check the literature for all staff members at SemanticScholar and make automatic updates based on the DOI information found there.  A rough sketch of this idea is here: https://docs.google.com/document/d/1uFyh5Z-wieksq_4Bf8Br7wHpN-buHECunS0VurYnlvg/edit?usp=sharing
