### ISSUE TITLE
Only show text on active icon in top bar

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#55]
I do not like the design of the top bar:

![image](https://user-images.githubusercontent.com/1818749/59656864-3534ef80-919f-11e9-8ed9-7518139b6f72.png)

It gives the feeling that the first 4 items, highlights to vacancies are important, and it is not even clear how the icon relates to the item, and then there are a few more items. I propose that instead we show text for all if that fits, if not you show icons only, but when you hover over an icon, the text appears, like this:

![image](https://user-images.githubusercontent.com/1818749/59657051-d0c66000-919f-11e9-9e53-20a37091e604.png)

The other thing I do not like, but I do not really know how to solve, is the icons themselves, I think if you would do a test and ask people based on only the icons to say what kind of page on a research group website you'd expect, they would not get very far.

**Comment by bramvanginneken** [comment]
A structure I would prefer is to have no news/highlights link, and no thesis gallery, you can show a thesis link on the publications page. Projects-presentations can also be merged, I would keep the video icon. The contact link could also be put elsewhere. Now if you click on Projects you get to a page titled Projects & Software, and it starts with software. This is poor design.

**Comment by wouterbulten** [comment]
Good points. During the beta test of the pathology website, the menu was probably the item that was discussed most (including picking the icons together with @GeertLitjens ). 

Just to clarify a few points:

- The menu and icons are configurable per website (in the config here https://github.com/DIAGNijmegen/website-content/blob/master/website-pathology/pelicanconf.py#L25). We assumed that each website could have different wishes for the website and its structure. For example, the RSE website has a completely different menu (see image below). For the DIAG website (which we are going to start working on soon), the menu should probably also be different. So in essence, each group is free to change the menu.

![image](https://user-images.githubusercontent.com/2886251/59660967-1c7e0700-91aa-11e9-95e1-a6fc776b1fd9.png)

- We can always add/change icons. We currently selected a list of icons that we support, but this can be extended. Only thing to consider: the icons have to be available through some kind of creative commons (or comparable) license and in SVG format.
- From a usability standpoint, icons are indeed less desirable than text. Only a few icons are almost universally recognized (e.g. the home icon, magnifying glass for search, print). You already pointed this out, for some menu items it is really difficult to find an icon that everyone understands. Given this I would favor text, if possible, for the most important pages. 
- Because there is limited space in the menu, we chose to show text for the primary links. On tablets and other small screens, the text disappears already (see below). For the pathology website we asked which items are the most important and which could be "hidden" using an icon. If other menu items should have precedence we can definitely do that, it's only a small change. Based on analytics of pathology website the following pages get the most views: members, highlights, projects and software/asap. For DIAG this differs slightly, with people, white matter lesions, vacancies and research being the most visited pages.
![image](https://user-images.githubusercontent.com/2886251/59662394-1f2e2b80-91ad-11e9-85c8-19a4ea543fae.png)

- Merging the thesis gallery and publications page seems like a good option and will free up some space in the menu.
- We could merge presentations and projects in to a new "Research" page. That could be a nice option for the DIAG website because we will need page anyway to show the different research groups that are part of DIAG.
- The presentations page is a bit of a pilot to see whether we think it is useful to display posters/presentation of the groups. So far this is under-used so we could even think of removing it.

@bramvanginneken maybe you could help us with the following:

1. If you have any preference/ideas for the menu of the DIAG website, let us know so we can take that as a base. I assume that there are menu items which are important or new ones which should be added (maybe the Open DDH?).
2. If you have any ideas about which icons to use let us know. A good place to search is https://icomoon.io/app/ (although not all icon packs are free). You can also send us a description so that we can find a icon that matches.

**Comment by wouterbulten** [comment]
Replaced by #182
