### ISSUE TITLE
Double ArXiv link in publication list

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#82]
In the publication list of the CP group is a double arXiv link visible with the preprint from Simpson et al (Simp19). I cannot discover anything weird in the bibkey.

**Comment by MeykeHermsen** [comment]
I see that the first ArXiv link appears when arxiv is listed as journal in the bibentry. The double link appears when the URL to the arxiv paper is filled in as well. 

For journal papers it is a nice feature that the link to the arxiv url is automatically named 'ArXiv', so I would not change this. In stead we could choose to not show the link to the URL in case of an ArXiv paper.

**Comment by ghumpire** [comment]
Just a hint for @martvanrijthoven, I think this can be fixed by adding a flag here. https://github.com/DIAGNijmegen/website-content/blob/01baa1f8bc5008aa5f8e3916fb4df0f86b802474/plugins/bib_writer.py#L389-L394

and in the code below verify the status of that flag. 

https://github.com/DIAGNijmegen/website-content/blob/01baa1f8bc5008aa5f8e3916fb4df0f86b802474/plugins/bib_writer.py#L401-L408

**Comment by martvanrijthoven** [comment]
@ghumpire  thanks for the hints!

This is fixed now.
