### ISSUE TITLE
change of home screen image/color

### ISSUE THREAD

**Issue by rashindra** [DIAGNijmegen/website-content#84]
**Is your feature request related to a problem? Please describe.**

Regarding the big blue bar on the home screen:

- can an option be added to change the height?
- I'd like to have the option to remove all text and have one big image (e.g. a highlight image) or multiple (highlight) images which (automatically) shifts
- or to change the color (to one of the grey scale colors which are also available in the Radboud color scheme)

**Describe the solution you'd like**

**Additional context (Optional)**

**Comment by wouterbulten** [comment]
@rashindra We introduced a new 'dense' setting for the homepage. I've enabled it for the neuro website. It makes the jumbotron significantly smaller in height.

**Comment by wouterbulten** [comment]
To add: it is now also possible to set the homepage image to 'highlight' mode. In that mode, instead of a default image, the image of the latest highlight is shown (with the title, and link to full article). See CPG or DIAG beta website for an example.

**Comment by wouterbulten** [comment]
I've implemented a small test with an alternative color scheme. Please see your website and let me know what you think.

**Comment by rashindra** [comment]
I like it. Thanks for adding the options. There is a small blue line still above the big-colored bar (that's called a jumbotron?) which should be removed. The logo bottom nicely matches with the grey color of the jumbotron color. Where can I play with the settings, e.g. also change the fonts color and type? 

Please note: I am not fully aware which feature requests would take a lot of work or can easily be achieved. E.g. I would simply would like to see text (top right for the menu) only instead of icons (which fold out), with the option to change naming (e.g. People instead of Member), and many other requests. I will make separate tickets for these requests.

**Comment by wouterbulten** [comment]
The menu (items, text, icons) can be changed through your pelicanconf, you are free to do so yourself. You can not change the url's though as they have to be the same for all websites. 

Regarding the color: We try to standardize the websites as much as possible to limit the amount of extra work we have to do for each individual website. We chose for the blue jumbotron to match the design of the Radboudumc website. It is possible to change the primary color of the website to grey instead of blue, this does require a custom css build though. 

Is there any staff-consensus on how much each website can differ? If there is a desire for more individuality between websites we can work on that.

**Comment by bramvanginneken** [comment]
I think it would be good Wouter if you would or a delegation of the webteam would give an update of the status, recent new things with a demo, and future plans and points for discussion in a staff meeting. You have made a lot of progress. I think there are still a few larger features missing, eg system for pdf downloads, but it looks very nice. There are a few open questions that I also think we should discuss in staff.

**Comment by wouterbulten** [comment]
Yes, sounds like a good plan. There are some things we would like to have input on.

We'll discuss it in our next webteam meeting and then I'll contact Charlotte for a meeting.

**Comment by MeykeHermsen** [comment]
Can we close this issue, Rashindra?
